### ISSUE TITLE
Crashing on successful injection (KERNEL & USERMODE)

### ISSUE THREAD

**Issue by ghost** [mactec0/Kernelmode-manual-mapping-through-IAT#5]
I'm attempting to inject my dll into a test application, but upon injection it almost instantly crashes.

Console log:
```
Attached to process GFXTest64.exe successfully...
Image base: 0x0000000016A80000
Stub base: 0x0000000016AA0000
Solving imports...
Solving relocations...
IAT function pointer: 0x00007FF744F89270
Mapping PE sections...
Entry point: 0x0000000016A8C50C
Injected successfully!
```

In my c++ code I'm simply just creating a new thread then calling the MessageBox macro, when doing this the application crashes:
```c++
BOOL APIENTRY DllMain(HMODULE hModule,
	DWORD  ul_reason_for_call,
	LPVOID lpReserved
)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		MessageBox(0, "Done.", "Injected", MB_OK | MB_ICONERROR);
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}
```

video of issue:
[video url](https://i.gyazo.com/7ed0853981539e5f2e1708b7d61970b9.mp4)

I also tested mmap with the USERMODE instead of KERNEL, with the same result.

Only changes i have made to mmap source is basic command line support so variables aren't hardcoded:
```c++
int main(int argc, char** argv)
{
	if (argc != 3) {
		std::cout << "[!] Incorrect usage. ( mmap.exe {process.exe} {path.dll} )" << std::endl;
		return 0;
	}

	mmap mapper(INJECTION_TYPE::KERNEL);

	if (!mapper.attach_to_process(argv[1]))
		return 1;

	if (!mapper.load_dll(argv[2]))
		return 1;

	if (!mapper.inject())
		return 1;

	return 0;
}
```

**Comment by mactec0** [comment]
DLL probably isn't compiled statically. Use project files with correct settings provided in  [releases](https://github.com/mactec0/Kernelmode-manual-mapping-through-IAT/releases). 
If it doesn't solve your issue, debug

**Comment by ghost** [comment]
I went through the settings to fit to your specifications, I added User32.lib to my additional dependencies, but I can't figure out which library file these come from:
[linker error](https://i.gyazo.com/eb1a8f51b106accca54a517c297f413b.png)

**Comment by mactec0** [comment]
Gdi32.lib
[https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getobjecta](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-getobjecta)

**Comment by ghost** [comment]
You are one of the fastest / best responses i have had on GitHub in a long while. Thank you very much mate.

[image of it working :)](https://i.gyazo.com/0c0d174bc22770c70e6e2748244fde70.png)
