### ISSUE TITLE
Packed Process Causing Issues

### ISSUE THREAD

**Issue by NMan1** [mactec0/Kernelmode-manual-mapping-through-IAT#6]
Hello, firstly thank you for this release, its been a great learning tool.

I've been tinkering with it and have been trying to get it to work on Rainbow Six (game was packed with vmprotect).  R6 doesn't import TranslateMesssage so I used SetCursorPos. When running the program it says 'Injected Successfully' yet nothing happens. I figured it was because the game was packed so I dumped it with Scylla and opened it in IDA. I was able to find the address for the import table and hard coded it in the program.

After running the program with the hardcoded iat adress the game will crash. The cause cant be the DLL as it works with notepad. I have all the correct settings aswell.

Any ideas what to do?

**Comment by brunph** [comment]
having the same problem.

**Comment by mactec0** [comment]
> I was able to find the address for the import table and hard coded it in the program.
Are you sure that this address is correct? 
VMP "probably" keeps those pointers encrypted.

Instead of using IAT you can use the vmt table, here is an example: https://github.com/mactec0/Kernelmode-manual-mapping-through-IAT/tree/swapchain_vmt_example

**Comment by NMan1** [comment]
Great example, thank you!
